### ISSUE TITLE
What is the difference between this extension and an extension `Dart Data Class Generator` from `hzgood`?

### ISSUE THREAD

**Issue by bambinoua** [ricardoemerson/dart-data-class-tools#4]
What is the difference between this extension and an extension `Dart Data Class Generator` from `hzgood` which has more than 90K downloads?

**Comment by ricardoemerson** [comment]
The user who originally created the extension was **bendixma,** and the last version he had made available was `0.5.5`. I'm not sure what happened, but they removed the extension from the Visual Studio Marketplace and also deleted the repository on GitHub. However, I had it installed in my user folder and started using it internally in my projects because there was no other extension available in the same version that I was using, as specified above.

I also have other extensions available, including the [Flutter Development Extensions Pack](https://marketplace.visualstudio.com/items?itemName=ricardo-emerson.flutter-development-extensions-pack) which is a package of extensions for Flutter and this package installed bendixma's extension. With the removal of the repository, it became difficult for me to keep the users who were already using the extension updated, so I decided to make the author's last extension available.

Currently, in my project, it is version `0.5.9`, but it is still the same as version `0.5.5`. To update the readme.md file and a pull request that I later reverted, I had to increment the version number in order to update it in the marketplace.

As for the differences, I can't exactly tell you everything that one has different from the other, but I have already noticed different behavior in generating JSON Serialization for more complex objects between the one you mentioned and this one, and I achieve better results with this one.

One detail I recently noticed was this:

Using hzgood's extension:

![image](https://github.com/ricardoemerson/dart-data-class-tools/assets/2879795/58c68823-4a33-4434-9e87-0a348c0e7a74)

Using bendixma's extension:

![image](https://github.com/ricardoemerson/dart-data-class-tools/assets/2879795/fca5ef29-8ad9-41c6-927f-feb667494c2d)

About the downloads, the hzgood extension was released in november of 2021 and my extension was released in august of 2022, so him extension have more time than mine.

So, it's up to each person to use whichever one suits their day-to-day work better.
